version: '3.9'

services:

  db:
    image: "postgres:alpine"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres

    ports:
      - 5432:5432

  adminer:
    image: adminer

    ports:
      - 8080:8080
