version: "3.9"

services:

  rabbitmq:

    image: rabbitmq:3-management-alpine

    hostname: 'my-rabbit'

    ports:
      - 5672:5672
      - 15672:15672

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=my_vhost
