version: '3.9'

services:

  worker:

    image: "python:slim"
    working_dir: "/app"
    volumes:
      - "../:/app"
    command: >
      bash -c "pip install -r requirements.txt
      && dramatiq-gevent app.notifications.tasks -p 8 -t 250
      "

    network_mode: "host"

