version: "3.9"

services:
  db:
    image: "postgres:alpine"
    restart: "unless-stopped"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres

    network_mode: "host"


  app:
    image: "python:slim"
    restart: "unless-stopped"

    depends_on:
      - db

    working_dir: "/app"

    env_file:
      - "../.env"

    environment:
      MATTERMOST_SITEURL: "http://mattermost:8065"

    volumes:
      - "../:/app"

    command: >
      bash -c "pip install -r requirements.txt
      && python3 patch_driver.py
      && flask init-db
      && bash run_app.sh
      "
    network_mode: "host"
